package com.iomt.android.room.basic

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Basic [Entity] with [id]
 */
@Entity
open class BasicEntity {
    /**
     * Autogenerated id, null by default
     */
    @PrimaryKey(autoGenerate = true)
    var id: Long? = null
}
